apiVersion: v1
kind: Service
metadata:
  name: citus
  labels:
    component: citus
spec:
  selector:
    component: citus
  ports:
  - port: 5432
  clusterIP: None

---

apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: citus
  labels:
    component: citus
spec:
  serviceName: citus
  template:
    metadata:
      name: citus
      labels:
        component: citus
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      containers:
      - name: citus
        image: jberkus/citus:0.9
        env:
        - name: POD_GROUP
          value: citus
        - name: SET_SIZE
          value: "7"
        - name: SUPERPASS
          valueFrom:
            secretKeyRef:
              name: citus
              key: password-superuser
        - name: ADMINPASS
          valueFrom:
            secretKeyRef:
              name: citus
              key: password-admin
        - name: REPPASS
          valueFrom:
            secretKeyRef:
              name: citus
              key: password-standby
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ETCD_HOST
          value: etcd.$(POD_NS).svc.cluster.local
        - name: LANG
          value: C.UTF8
        ports:
        - containerPort: 5432
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
        volumeMounts:
        - name: pgdata
          mountPath: /pgdata
        - mountPath: /tmp/citus
          name: citus-config
          readOnly: true
      volumes:
      - name: citus-config
        secret:
          secretName: citus
      - name: pgdata
        emptyDir: {}
